spring:
  datasource:
    url: jdbc:mysql://localhost:3300/Spring?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ckdgus
    password: 5824
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace